<?php
/**
 * @var $block \OrviSoft\RelatedCategory\Block\Customers
 */
	$_product = $this->getProduct();
?>
<div>
	<!-- <?= $block->getAlsoViewed() ?> -->
	<!-- <?= __('Hello OrviSoft_RelatedCategory::customers_also_viewed.phtml') ?> -->
</div>
<div class="more-products-option">
<h3><strong>Customers Also Viewed</strong></h3>
   <ul class="row owl-carousel">
      <li class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
               <a class="product-image" href="/" tabindex="-1">
               <span class="babyfoots-media-container product-list-promo-container">
               <img class="product-image-photo default_image porto-lazyload porto-lazyload-loaded" data-src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/b/c/bcfa9232c86bb9956a4cc1cdc165083f_3.jpg" width="250" height="250" src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/b/c/bcfa9232c86bb9956a4cc1cdc165083f_3.jpg" style="display: block;">
               </span>
               </a>
            </div>
            <div class="product details product-item-details">
               <div class="product description product-item-description">
                  <ul class="listing-short-description homepage">
                     <li>AMD Ryzen  , 2.30 GHz Processor</li>
                     <li>14 in  , 1920 x 1080</li>
                     <li>8 GB RAM  , 256GB SSD </li>
                     <li>Integrated/On-Board Graphics</li>
                     <li>Windows 10  , Starter</li>
                  </ul>
                  
               </div>
               <div class="price-box price-final_price" data-role="priceBox" data-product-id="7965" data-price-box="product-id-7965">
                  <span class="special-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Now</span>
                  <span id="product-price-7965" data-price-amount="559.99" data-price-type="finalPrice" class="price-wrapper "><span class="price">£459.99</span></span>
                  </span>
                  </span>
                  <span class="save-was-price">
                  <span class="old-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Was</span>
                  <span id="old-price-7965" data-price-amount="649.99" data-price-type="oldPrice" class="price-wrapper "><span class="price">£549.99</span></span>
                  </span>
                  </span>
                  <span class="slash">/</span>
                  <span class="save-price">
                  <span class="price-container price-save_price">
                  <span class="price-label">Save</span>
                  <span id="save-price" data-price-amount="90" data-price-type="savePrice" class="price-wrapper "><span class="price">£90</span></span>
                  </span>
                  </span>
                  </span>
               </div>
            </div>
         </div>
      </li>
	  <li class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
               <a class="product-image" href="/" tabindex="-1">
               <span class="babyfoots-media-container product-list-promo-container">
               <img class="product-image-photo default_image porto-lazyload porto-lazyload-loaded" data-src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/2/1/210974244b919ce9400666f6def1c08b_1.jpg" width="250" height="250" src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/2/1/210974244b919ce9400666f6def1c08b_1.jpg" style="display: block;">
               </span>
               </a>
            </div>
            <div class="product details product-item-details">
               <div class="product description product-item-description">
                  <ul class="listing-short-description homepage">
                     <li>AMD Ryzen  , 2.30 GHz Processor</li>
                     <li>14 in  , 1920 x 1080</li>
                     <li>8 GB RAM  , 512GB SSD </li>
                     <li>Integrated/On-Board Graphics</li>
                     <li>Windows 10  , Starter</li>
                  </ul>
                  
               </div>
               <div class="price-box price-final_price" data-role="priceBox" data-product-id="7965" data-price-box="product-id-7965">
                  <span class="special-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Now</span>
                  <span id="product-price-7965" data-price-amount="559.99" data-price-type="finalPrice" class="price-wrapper "><span class="price">£559.99</span></span>
                  </span>
                  </span>
                  <span class="save-was-price">
                  <span class="old-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Was</span>
                  <span id="old-price-7965" data-price-amount="649.99" data-price-type="oldPrice" class="price-wrapper "><span class="price">£649.99</span></span>
                  </span>
                  </span>
                  <span class="slash">/</span>
                  <span class="save-price">
                  <span class="price-container price-save_price">
                  <span class="price-label">Save</span>
                  <span id="save-price" data-price-amount="90" data-price-type="savePrice" class="price-wrapper "><span class="price">£90</span></span>
                  </span>
                  </span>
                  </span>
               </div>
            </div>
         </div>
      </li>
	  <li class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
               <a class="product-image" href="/" tabindex="-1">
               <span class="babyfoots-media-container product-list-promo-container">
               <img class="product-image-photo default_image porto-lazyload porto-lazyload-loaded" data-src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/5/9/597a6fee93f42c65b756f63413cd742b_1.jpg" width="250" height="250" src="https://dev.fivetech.co.uk/pub/media/catalog/product/cache/0eba8f40f2f2d3c163a23e49371f3f0c/5/9/597a6fee93f42c65b756f63413cd742b_1.jpg" style="display: block;">
               </span>
               </a>
            </div>
            <div class="product details product-item-details">
               <div class="product description product-item-description">
                  <ul class="listing-short-description homepage">
                     <li>Intel Core i7 , 2.60 GHz Processor</li>
                     <li>15.6 in  , 1920 x 1080</li>
                     <li>16 GB RAM  , 512GB SSD </li>
                     <li>Integrated/On-Board Graphics</li>
                     <li>Windows 10  , Starter</li>
                  </ul>
                  
               </div>
               <div class="price-box price-final_price" data-role="priceBox" data-product-id="7965" data-price-box="product-id-7965">
                  <span class="special-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Now</span>
                  <span id="product-price-7965" data-price-amount="559.99" data-price-type="finalPrice" class="price-wrapper "><span class="price">£759.99</span></span>
                  </span>
                  </span>
                  <span class="save-was-price">
                  <span class="old-price">
                  <span class="price-container price-final_price tax weee">
                  <span class="price-label">Was</span>
                  <span id="old-price-7965" data-price-amount="649.99" data-price-type="oldPrice" class="price-wrapper "><span class="price">£849.99</span></span>
                  </span>
                  </span>
                  <span class="slash">/</span>
                  <span class="save-price">
                  <span class="price-container price-save_price">
                  <span class="price-label">Save</span>
                  <span id="save-price" data-price-amount="90" data-price-type="savePrice" class="price-wrapper "><span class="price">£90</span></span>
                  </span>
                  </span>
                  </span>
               </div>
            </div>
         </div>
      </li>
   </ul>
   <script type="text/javascript">
		require([
			'jquery',
			'owl.carousel/owl.carousel.min'
		], function($) {
			$(".more-products-option .owl-carousel").owlCarousel({
				autoplay: true,
				autoplayTimeout: 5000,
				autoplayHoverPause: true,
				margin: 30,
				nav: true,
				navText: ["<em class='porto-icon-chevron-left'></em>", "<em class='porto-icon-chevron-right'></em>"],
				dots: false,
				loop: true,
				responsive: {
					0: {
						items: 1,
						slideBy: 1
					},
					640: {
						items: 2,
						slideBy: 2
					},
					768: {
						items: 3,
						slideBy: 3
					}
					
				}
			});
		});
	</script>
</div>