<?php
/**
 * @var $block \OrviSoft\RelatedCategory\Block\Customers
 */
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$currencysymbol = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$currencyCode = $currencysymbol->getStore()->getCurrentCurrencyCode();
$currency =  $objectManager->create('Magento\Directory\Model\CurrencyFactory')->create()->load($currencyCode);
$currencySymbol = $currency->getCurrencySymbol();
	$product = $_product = $this->getProduct();
	$categories = $_product->getCategoryIds();
	$categoryid = false;
	$_cats = array();
	foreach ($categories as $category_id) {
		//echo $category_id. '<br />';
		$categoryid = $category_id;
		//break 1;
		// $_cats[] = $category_id;
		$_cat = $this->getCategory($category_id) ;
		if($_cat->getRelatedCategory()){
			//$categoryid = $_cat->getRelatedCategory();
			$_cats[] = $category_id;
			//break 1;
		}
	}
	if(!count($_cats)){
		return;
	}
	$products = $this->getAlsoViewed($_cats, $_product->getFinalPrice());
	if(!$products){
		return;
	}

	$_category_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category');
	$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
	$image_width = ($_category_config['ratio_width'])?$_category_config['ratio_width']:300;
	$image_height = ($_category_config['ratio_height'])?$_category_config['ratio_height']:300;
	$image = 'category_page_list';
    if($_category_config['aspect_ratio'])
        $image_height = $image_width;
?>

<div class="more-products-option">
<h3><strong>Customers Also Viewed</strong></h3>
   <ul class="row owl-carousel">
   <?php foreach($products as $_product): ?>
      <li class="item product product-item">
         <div class="product-item-info" data-container="product-grid">
            <div class="product photo product-item-photo">
               <a class="product-image" href="<?php $_product->getProductUrl(); ?>" tabindex="-1">
               <span class="babyfoots-media-container product-list-promo-container">
			   <?php
				$productImage = $_imagehelper->init($_product, $image)->resize($image_width, $image_height);
				$productImageUrl = $productImage->getUrl();
			   ?>
               <img class="product-image-photo default_image porto-lazyload porto-lazyload-loaded" src="<?php echo $productImageUrl; ?>" data-src="<?php echo $productImageUrl; ?>" width="<?php echo $image_height; ?>" height="<?php echo $image_height; ?>" style="display: block;">
               </span>
               </a>
            </div>
            <div class="product details product-item-details">
               <div class="product description product-item-description">
				  <ul class="listing-short-description homepage">
					<?php if(strlen($_product->getData('processor_type')) || $_product->getData('processor_speed')): ?>
					<li><?php echo (strlen($_product->getData('processor_type')) >0 ? $_product->getResource()->getAttribute('processor_type')->getFrontend()->getValue($_product) : ''); ?> <?php echo (strlen($_product->getData('processor_speed')) >0 ? ' , '.$_product->getResource()->getAttribute('processor_speed')->getFrontend()->getValue($_product): ''); ?> Processor</li>
					<?php endif; ?>
					<?php if(strlen($_product->getData('screen_size')) || $_product->getData('maximum_resolution')): ?>
					<li><?php echo (strlen($_product->getData('screen_size')) >0 ? $_product->getResource()->getAttribute('screen_size')->getFrontend()->getValue($_product) : ''); ?> <?php echo (strlen($_product->getData('maximum_resolution')) >0 ? ' , '.$_product->getResource()->getAttribute('maximum_resolution')->getFrontend()->getValue($_product): ''); ?></li>
					<?php endif; ?>
					<?php if(strlen($_product->getData('ram_size')) || $_product->getData('ssd_capacity') || $_product->getData('hard_drive_capacity')): ?>
					<li><?php echo (strlen($_product->getData('ram_size')) >0 ? $_product->getData('ram_size').' RAM' : ''); ?> <?php echo (strlen($_product->getData('ssd_capacity')) >0 ? ' , '.$_product->getResource()->getAttribute('ssd_capacity')->getFrontend()->getValue($_product).' SSD' : ''); ?> <?php echo (strlen($_product->getData('hard_drive_capacity')) >0 ? ' , '.$_product->getResource()->getAttribute('hard_drive_capacity')->getFrontend()->getValue($_product).' HDD': ''); ?></li>
					<?php endif; ?>
					<?php if(strlen($_product->getData('graphics_processing_type'))): ?>
					<li><?php echo (strlen($_product->getData('graphics_processing_type')) >0 ? $_product->getResource()->getAttribute('graphics_processing_type')->getFrontend()->getValue($_product) : ''); ?></li>
					<?php endif; ?>

					<?php if(strlen($_product->getData('operating_system')) || $_product->getData('operating_system_edition')): ?>
					<li><?php echo (strlen($_product->getData('operating_system')) >0 ? $_product->getResource()->getAttribute('operating_system')->getFrontend()->getValue($_product) : ''); ?> <?php echo (strlen($_product->getData('operating_system_edition')) >0 ? ' , '.$_product->getResource()->getAttribute('operating_system_edition')->getFrontend()->getValue($_product): ''); ?></li>
					<?php endif; ?>
				</ul>
               </div>
			   <?php //buggy method //echo $this->getLayout()->createBlock('OrviSoft\AddonProducts\Block\Home')->getProductPrice($_product) ?>
			   <div class="price-box price-final_price"><?php echo $currencySymbol . ' ' . round($_product->getFinalPrice(), 2); ?></div>
            </div>
         </div>
      </li>
	<?php endforeach; ?>
	  
   </ul>
   <script type="text/javascript">
		require([
			'jquery',
			'owl.carousel/owl.carousel.min'
		], function($) {
			$(".more-products-option .owl-carousel").owlCarousel({
				autoplay: true,
				autoplayTimeout: 5000,
				autoplayHoverPause: true,
				margin: 30,
				nav: true,
				navText: ["<em class='porto-icon-chevron-left'></em>", "<em class='porto-icon-chevron-right'></em>"],
				dots: false,
				loop: true,
				responsive: {
					0: {
						items: 1,
						slideBy: 1
					},
					640: {
						items: 2,
						slideBy: 2
					},
					768: {
						items: 3,
						slideBy: 3
					}
					
				}
			});
		});
	</script>
</div>